name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

env:
  python-version: '3.7'
  node-version: '14.x'

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~\AppData\Local\pip\Cache
            env
            ${{ steps.npm-cache.outputs.dir }}
            libs
          key: ${{ runner.os }}-pip-node-virtualenv-cpplint-${{ hashFiles('**/package-lock.json', 'build.js') }}
          restore-keys: |
            ${{ runner.os }}-pip-node-
            ${{ runner.os }}-
      - name: Install virtualenv
        run: python -m pip install virtualenv
      - name: Create a virtual environment
        run: virtualenv env
      - name: Install cpplint
        run: |
          env\Scripts\activate
          python -m pip install cpplint
          env\Scripts\deactivate
      - name: Install dependencies
        run: npm ci
      - name: Lint project
        run: |
          env\Scripts\activate
          cpplint --recursive --linelength=256 nitro\src\
          env\Scripts\deactivate
  build-test-app:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Cache project
        uses: actions/cache@v2
        with:
          path: |
            libs
            nitro\Test
            nitro\x64\Test
          key: ${{ runner.os }}-pip-node-virtualenv-cpplint-${{ hashFiles('**/package-lock.json', 'build.js') }}
          restore-keys: |
            ${{ runner.os }}-pip-node-
            ${{ runner.os }}-
      - run: msbuild nitro\nitro.sln /p:Configuration=Test /p:Platform=x86
      - run: msbuild nitro\nitro.sln /p:Configuration=Test /p:Platform=x64
    needs: lint
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Cache project
        uses: actions/cache@v2
        with:
          path: |
            nitro\Test
            nitro\x64\Test
          key: ${{ runner.os }}-pip-node-virtualenv-cpplint-${{ hashFiles('**/package-lock.json', 'build.js') }}
          restore-keys: |
            ${{ runner.os }}-pip-node-
            ${{ runner.os }}-
      - name: Test x86
        run: |
          cd nitro
          Test\nitro.exe
          cd ..
      - name: Test x64
        run: |
          cd nitro
          x64\Test\nitro.exe
          cd ..
    needs: build-test-app
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Cache project
        uses: actions/cache@v2
        with:
          path: |
            libs
            **\Debug
            **\Release
          key: ${{ runner.os }}-pip-node-virtualenv-cpplint-${{ hashFiles('**/package-lock.json', 'build.js') }}
          restore-keys: |
            ${{ runner.os }}-pip-node-
            ${{ runner.os }}-
      - run: msbuild nitro\nitro.sln /p:Configuration=Debug /p:Platform=x86
      - run: msbuild nitro\nitro.sln /p:Configuration=Debug /p:Platform=x64
      - run: msbuild nitro\nitro.sln /p:Configuration=Release /p:Platform=x86
      - run: msbuild nitro\nitro.sln /p:Configuration=Release /p:Platform=x64
    needs: lint
  deploy:
    if: github.base_ref == 'master'
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache project
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            **\Debug
            **\Release
          key: ${{ runner.os }}-pip-node-virtualenv-cpplint-${{ hashFiles('**/package-lock.json', 'build.js') }}
          restore-keys: |
            ${{ runner.os }}-pip-node-
            ${{ runner.os }}-
      - run: node deploy.js 1.3.0 ${{ secrets.DEPLOY_TOKEN }}
    needs: [test, build]
